<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['currency_id' => 1, 'common' => 'Afghanistan', 'official' => 'Islamic Republic of Afghanistan', 'cca2' => 'AF', 'ccn3' => '004', 'cca3' => 'AFG', 'flag' => 'af.svg', 'subregion_id' => '20'],
            ['currency_id' => 48, 'common' => 'Åland Islands', 'official' => 'Åland Islands', 'cca2' => 'AX', 'ccn3' => '248', 'cca3' => 'ALA', 'flag' => 'ax.svg', 'subregion_id' => '15'],
            ['currency_id' => 2, 'common' => 'Albania', 'official' => 'Republic of Albania', 'cca2' => 'AL', 'ccn3' => '008', 'cca3' => 'ALB', 'flag' => 'al.svg', 'subregion_id' => '21'],
            ['currency_id' => 3, 'common' => 'Algeria', 'official' => "People's Democratic Republic of Algeria", 'cca2' => 'DZ', 'ccn3' => '012', 'cca3' => 'DZA', 'flag' => 'dz.svg', 'subregion_id' => '13'],
            ['currency_id' => 146, 'common' => 'American Samoa', 'official' => 'American Samoa', 'cca2' => 'AS', 'ccn3' => '016', 'cca3' => 'ASM', 'flag' => 'as.svg', 'subregion_id' => '16'],
            ['currency_id' => 48, 'common' => 'Andorra', 'official' => 'Principality of Andorra', 'cca2' => 'AD', 'ccn3' => '020', 'cca3' => 'AND', 'flag' => 'ad.svg', 'subregion_id' => '21'],
            ['currency_id' => 4, 'common' => 'Angola', 'official' => 'Republic of Angola', 'cca2' => 'AO', 'ccn3' => '024', 'cca3' => 'AGO', 'flag' => 'ao.svg', 'subregion_id' => '12'],
            ['currency_id' => 44, 'common' => 'Anguilla', 'official' => 'Anguilla', 'cca2' => 'AI', 'ccn3' => '660', 'cca3' => 'AIA', 'flag' => 'ai.svg', 'subregion_id' => '3'],
            ['currency_id' => 8, 'common' => 'Antarctica', 'official' => 'Antarctica', 'cca2' => 'AQ', 'ccn3' => '010', 'cca3' => 'ATA', 'flag' => 'aq.svg', 'subregion_id' => '1'],
            ['currency_id' => 44, 'common' => 'Antigua and Barbuda', 'official' => 'Antigua and Barbuda', 'cca2' => 'AG', 'ccn3' => '028', 'cca3' => 'ATG', 'flag' => 'ag.svg', 'subregion_id' => '3'],
            ['currency_id' => 5, 'common' => 'Argentina', 'official' => 'Argentine Republic', 'cca2' => 'AR', 'ccn3' => '032', 'cca3' => 'ARG', 'flag' => 'ar.svg', 'subregion_id' => '17'],
            ['currency_id' => 6, 'common' => 'Armenia', 'official' => 'Republic of Armenia', 'cca2' => 'AM', 'ccn3' => '051', 'cca3' => 'ARM', 'flag' => 'am.svg', 'subregion_id' => '23'],
            ['currency_id' => 7, 'common' => 'Aruba', 'official' => 'Aruba', 'cca2' => 'AW', 'ccn3' => '533', 'cca3' => 'ABW', 'flag' => 'aw.svg', 'subregion_id' => '3'],
            ['currency_id' => 8, 'common' => 'Australia', 'official' => 'Commonwealth of Australia', 'cca2' => 'AU', 'ccn3' => '036', 'cca3' => 'AUS', 'flag' => 'au.svg', 'subregion_id' => '2'],
            ['currency_id' => 48, 'common' => 'Austria', 'official' => 'Republic of Austria', 'cca2' => 'AT', 'ccn3' => '040', 'cca3' => 'AUT', 'flag' => 'at.svg', 'subregion_id' => '6'],
            ['currency_id' => 9, 'common' => 'Azerbaijan', 'official' => 'Republic of Azerbaijan', 'cca2' => 'AZ', 'ccn3' => '031', 'cca3' => 'AZE', 'flag' => 'az.svg', 'subregion_id' => '23'],
            ['currency_id' => 10, 'common' => 'Bahamas', 'official' => 'Commonwealth of the Bahamas', 'cca2' => 'BS', 'ccn3' => '044', 'cca3' => 'BHS', 'flag' => 'bs.svg', 'subregion_id' => '3'],
            ['currency_id' => 11, 'common' => 'Bahrain', 'official' => 'Kingdom of Bahrain', 'cca2' => 'BH', 'ccn3' => '048', 'cca3' => 'BHR', 'flag' => 'bh.svg', 'subregion_id' => '23'],
            ['currency_id' => 12, 'common' => 'Bangladesh', 'official' => "People's Republic of Bangladesh", 'cca2' => 'BD', 'ccn3' => '050', 'cca3' => 'BGD', 'flag' => 'bd.svg', 'subregion_id' => '20'],
            ['currency_id' => 13, 'common' => 'Barbados', 'official' => 'Barbados', 'cca2' => 'BB', 'ccn3' => '052', 'cca3' => 'BRB', 'flag' => 'bb.svg', 'subregion_id' => '3'],
            ['currency_id' => 97, 'common' => 'Belarus', 'official' => 'Republic of Belarus', 'cca2' => 'BY', 'ccn3' => '112', 'cca3' => 'BLR', 'flag' => 'by.svg', 'subregion_id' => '9'],
            ['currency_id' => 48, 'common' => 'Belgium', 'official' => 'Kingdom of Belgium', 'cca2' => 'BE', 'ccn3' => '056', 'cca3' => 'BEL', 'flag' => 'be.svg', 'subregion_id' => '24'],
            ['currency_id' => 14, 'common' => 'Belize', 'official' => 'Belize', 'cca2' => 'BZ', 'ccn3' => '084', 'cca3' => 'BLZ', 'flag' => 'bz.svg', 'subregion_id' => '4'],
            ['currency_id' => 153, 'common' => 'Benin', 'official' => 'Republic of Benin', 'cca2' => 'BJ', 'ccn3' => '204', 'cca3' => 'BEN', 'flag' => 'bj.svg', 'subregion_id' => '22'],
            ['currency_id' => 15, 'common' => 'Bermuda', 'official' => 'Bermuda', 'cca2' => 'BM', 'ccn3' => '060', 'cca3' => 'BMU', 'flag' => 'bm.svg', 'subregion_id' => '14'],
            ['currency_id' => 16, 'common' => 'Bhutan', 'official' => 'Kingdom of Bhutan', 'cca2' => 'BT', 'ccn3' => '064', 'cca3' => 'BTN', 'flag' => 'bt.svg', 'subregion_id' => '20'],
            ['currency_id' => 17, 'common' => 'Bolivia', 'official' => 'Plurinational State of Bolivia', 'cca2' => 'BO', 'ccn3' => '068', 'cca3' => 'BOL', 'flag' => 'bo.svg', 'subregion_id' => '17'],
            ['currency_id' => 18, 'common' => 'Bosnia and Herzegovina', 'official' => 'Bosnia and Herzegovina', 'cca2' => 'BA', 'ccn3' => '070', 'cca3' => 'BIH', 'flag' => 'ba.svg', 'subregion_id' => '21'],
            ['currency_id' => 19, 'common' => 'Botswana', 'official' => 'Republic of Botswana', 'cca2' => 'BW', 'ccn3' => '072', 'cca3' => 'BWA', 'flag' => 'bw.svg', 'subregion_id' => '19'],
            ['currency_id' => 103, 'common' => 'Bouvet Island', 'official' => 'Bouvet Island', 'cca2' => 'BV', 'ccn3' => '074', 'cca3' => 'BVT', 'flag' => 'bv.svg', 'subregion_id' => '1'],
            ['currency_id' => 20, 'common' => 'Brazil', 'official' => 'Federative Republic of Brazil', 'cca2' => 'BR', 'ccn3' => '076', 'cca3' => 'BRA', 'flag' => 'br.svg', 'subregion_id' => '17'],
            ['currency_id' => 146, 'common' => 'British Indian Ocean Territory', 'official' => 'British Indian Ocean Territory', 'cca2' => 'IO', 'ccn3' => '086', 'cca3' => 'IOT', 'flag' => 'io.svg', 'subregion_id' => '7'],
            ['currency_id' => 146, 'common' => 'British Virgin Islands', 'official' => 'Virgin Islands', 'cca2' => 'VG', 'ccn3' => '092', 'cca3' => 'VGB', 'flag' => 'vg.svg', 'subregion_id' => '3'],
            ['currency_id' => 22, 'common' => 'Brunei', 'official' => 'Nation of Brunei, Abode of Peace', 'cca2' => 'BN', 'ccn3' => '096', 'cca3' => 'BRN', 'flag' => 'bn.svg', 'subregion_id' => '18'],
            ['currency_id' => 23, 'common' => 'Bulgaria', 'official' => 'Republic of Bulgaria', 'cca2' => 'BG', 'ccn3' => '100', 'cca3' => 'BGR', 'flag' => 'bg.svg', 'subregion_id' => '21'],
            ['currency_id' => 153, 'common' => 'Burkina Faso', 'official' => 'Burkina Faso', 'cca2' => 'BF', 'ccn3' => '854', 'cca3' => 'BFA', 'flag' => 'bf.svg', 'subregion_id' => '22'],
            ['currency_id' => 25, 'common' => 'Burundi', 'official' => 'Republic of Burundi', 'cca2' => 'BI', 'ccn3' => '108', 'cca3' => 'BDI', 'flag' => 'bi.svg', 'subregion_id' => '7'],
            ['currency_id' => 26, 'common' => 'Cambodia', 'official' => 'Kingdom of Cambodia', 'cca2' => 'KH', 'ccn3' => '116', 'cca3' => 'KHM', 'flag' => 'kh.svg', 'subregion_id' => '18'],
            ['currency_id' => 30, 'common' => 'Cameroon', 'official' => 'Republic of Cameroon', 'cca2' => 'CM', 'ccn3' => '120', 'cca3' => 'CMR', 'flag' => 'cm.svg', 'subregion_id' => '12'],
            ['currency_id' => 27, 'common' => 'Canada', 'official' => 'Canada', 'cca2' => 'CA', 'ccn3' => '124', 'cca3' => 'CAN', 'flag' => 'ca.svg', 'subregion_id' => '14'],
            ['currency_id' => 28, 'common' => 'Cape Verde', 'official' => 'Republic of Cabo Verde', 'cca2' => 'CV', 'ccn3' => '132', 'cca3' => 'CPV', 'flag' => 'cv.svg', 'subregion_id' => '22'],
            ['currency_id' => 146, 'common' => 'Caribbean Netherlands', 'official' => 'Bonaire, Sint Eustatius and Saba', 'cca2' => 'BQ', 'ccn3' => '535', 'cca3' => 'BES', 'flag' => 'bq.svg', 'subregion_id' => '3'],
            ['currency_id' => 29, 'common' => 'Cayman Islands', 'official' => 'Cayman Islands', 'cca2' => 'KY', 'ccn3' => '136', 'cca3' => 'CYM', 'flag' => 'ky.svg', 'subregion_id' => '3'],
            ['currency_id' => 30, 'common' => 'Central African Republic', 'official' => 'Central African Republic', 'cca2' => 'CF', 'ccn3' => '140', 'cca3' => 'CAF', 'flag' => 'cf.svg', 'subregion_id' => '12'],
            ['currency_id' => 30, 'common' => 'Chad', 'official' => 'Republic of Chad', 'cca2' => 'TD', 'ccn3' => '148', 'cca3' => 'TCD', 'flag' => 'td.svg', 'subregion_id' => '12'],
            ['currency_id' => 32, 'common' => 'Chile', 'official' => 'Republic of Chile', 'cca2' => 'CL', 'ccn3' => '152', 'cca3' => 'CHL', 'flag' => 'cl.svg', 'subregion_id' => '17'],
            ['currency_id' => 33, 'common' => 'China', 'official' => "People's Republic of China", 'cca2' => 'CN', 'ccn3' => '156', 'cca3' => 'CHN', 'flag' => 'cn.svg', 'subregion_id' => '8'],
            ['currency_id' => 8, 'common' => 'Christmas Island', 'official' => 'Territory of Christmas Island', 'cca2' => 'CX', 'ccn3' => '162', 'cca3' => 'CXR', 'flag' => 'cx.svg', 'subregion_id' => '2'],
            ['currency_id' => 8, 'common' => 'Cocos (Keeling) Islands', 'official' => 'Territory of the Cocos (Keeling) Islands', 'cca2' => 'CC', 'ccn3' => '166', 'cca3' => 'CCK', 'flag' => 'cc.svg', 'subregion_id' => '2'],
            ['currency_id' => 34, 'common' => 'Colombia', 'official' => 'Republic of Colombia', 'cca2' => 'CO', 'ccn3' => '170', 'cca3' => 'COL', 'flag' => 'co.svg', 'subregion_id' => '17'],
            ['currency_id' => 35, 'common' => 'Comoros', 'official' => 'Union of the Comoros', 'cca2' => 'KM', 'ccn3' => '174', 'cca3' => 'COM', 'flag' => 'km.svg', 'subregion_id' => '7'],
            ['currency_id' => 99, 'common' => 'Cook Islands', 'official' => 'Cook Islands', 'cca2' => 'CK', 'ccn3' => '184', 'cca3' => 'COK', 'flag' => 'ck.svg', 'subregion_id' => '16'],
            ['currency_id' => 37, 'common' => 'Costa Rica', 'official' => 'Republic of Costa Rica', 'cca2' => 'CR', 'ccn3' => '188', 'cca3' => 'CRI', 'flag' => 'cr.svg', 'subregion_id' => '4'],
            ['currency_id' => 38, 'common' => 'Croatia', 'official' => 'Republic of Croatia', 'cca2' => 'HR', 'ccn3' => '191', 'cca3' => 'HRV', 'flag' => 'hr.svg', 'subregion_id' => '21'],
            ['currency_id' => 39, 'common' => 'Cuba', 'official' => 'Republic of Cuba', 'cca2' => 'CU', 'ccn3' => '192', 'cca3' => 'CUB', 'flag' => 'cu.svg', 'subregion_id' => '3'],
            ['currency_id' => 96, 'common' => 'Curaçao', 'official' => 'Country of Curaçao', 'cca2' => 'CW', 'ccn3' => '531', 'cca3' => 'CUW', 'flag' => 'cw.svg', 'subregion_id' => '3'],
            ['currency_id' => 48, 'common' => 'Cyprus', 'official' => 'Republic of Cyprus', 'cca2' => 'CY', 'ccn3' => '196', 'cca3' => 'CYP', 'flag' => 'cy.svg', 'subregion_id' => '21'],
            ['currency_id' => 40, 'common' => 'Czechia', 'official' => 'Czech Republic', 'cca2' => 'CZ', 'ccn3' => '203', 'cca3' => 'CZE', 'flag' => 'cz.svg', 'subregion_id' => '6'],
            ['currency_id' => 41, 'common' => 'Denmark', 'official' => 'Kingdom of Denmark', 'cca2' => 'DK', 'ccn3' => '208', 'cca3' => 'DNK', 'flag' => 'dk.svg', 'subregion_id' => '15'],
            ['currency_id' => 42, 'common' => 'Djibouti', 'official' => 'Republic of Djibouti', 'cca2' => 'DJ', 'ccn3' => '262', 'cca3' => 'DJI', 'flag' => 'dj.svg', 'subregion_id' => '7'],
            ['currency_id' => 44, 'common' => 'Dominica', 'official' => 'Commonwealth of Dominica', 'cca2' => 'DM', 'ccn3' => '212', 'cca3' => 'DMA', 'flag' => 'dm.svg', 'subregion_id' => '3'],
            ['currency_id' => 43, 'common' => 'Dominican Republic', 'official' => 'Dominican Republic', 'cca2' => 'DO', 'ccn3' => '214', 'cca3' => 'DOM', 'flag' => 'do.svg', 'subregion_id' => '3'],
            ['currency_id' => 36, 'common' => 'DR Congo', 'official' => 'Democratic Republic of the Congo', 'cca2' => 'CD', 'ccn3' => '180', 'cca3' => 'COD', 'flag' => 'cd.svg', 'subregion_id' => '12'],
            ['currency_id' => 146, 'common' => 'Ecuador', 'official' => 'Republic of Ecuador', 'cca2' => 'EC', 'ccn3' => '218', 'cca3' => 'ECU', 'flag' => 'ec.svg', 'subregion_id' => '17'],
            ['currency_id' => 45, 'common' => 'Egypt', 'official' => 'Arab Republic of Egypt', 'cca2' => 'EG', 'ccn3' => '818', 'cca3' => 'EGY', 'flag' => 'eg.svg', 'subregion_id' => '13'],
            ['currency_id' => 146, 'common' => 'El Salvador', 'official' => 'Republic of El Salvador', 'cca2' => 'SV', 'ccn3' => '222', 'cca3' => 'SLV', 'flag' => 'sv.svg', 'subregion_id' => '4'],
            ['currency_id' => 30, 'common' => 'Equatorial Guinea', 'official' => 'Republic of Equatorial Guinea', 'cca2' => 'GQ', 'ccn3' => '226', 'cca3' => 'GNQ', 'flag' => 'gq.svg', 'subregion_id' => '12'],
            ['currency_id' => 46, 'common' => 'Eritrea', 'official' => 'State of Eritrea', 'cca2' => 'ER', 'ccn3' => '232', 'cca3' => 'ERI', 'flag' => 'er.svg', 'subregion_id' => '7'],
            ['currency_id' => 48, 'common' => 'Estonia', 'official' => 'Republic of Estonia', 'cca2' => 'EE', 'ccn3' => '233', 'cca3' => 'EST', 'flag' => 'ee.svg', 'subregion_id' => '15'],
            ['currency_id' => 131, 'common' => 'Eswatini', 'official' => 'Kingdom of Eswatini', 'cca2' => 'SZ', 'ccn3' => '748', 'cca3' => 'SWZ', 'flag' => 'sz.svg', 'subregion_id' => '19'],
            ['currency_id' => 47, 'common' => 'Ethiopia', 'official' => 'Federal Democratic Republic of Ethiopia', 'cca2' => 'ET', 'ccn3' => '231', 'cca3' => 'ETH', 'flag' => 'et.svg', 'subregion_id' => '7'],
            ['currency_id' => 49, 'common' => 'Falkland Islands', 'official' => 'Falkland Islands', 'cca2' => 'FK', 'ccn3' => '238', 'cca3' => 'FLK', 'flag' => 'fk.svg', 'subregion_id' => '17'],
            ['currency_id' => 41, 'common' => 'Faroe Islands', 'official' => 'Faroe Islands', 'cca2' => 'FO', 'ccn3' => '234', 'cca3' => 'FRO', 'flag' => 'fo.svg', 'subregion_id' => '15'],
            ['currency_id' => 50, 'common' => 'Fiji', 'official' => 'Republic of Fiji', 'cca2' => 'FJ', 'ccn3' => '242', 'cca3' => 'FJI', 'flag' => 'fj.svg', 'subregion_id' => '10'],
            ['currency_id' => 48, 'common' => 'Finland', 'official' => 'Republic of Finland', 'cca2' => 'FI', 'ccn3' => '246', 'cca3' => 'FIN', 'flag' => 'fi.svg', 'subregion_id' => '15'],
            ['currency_id' => 48, 'common' => 'France', 'official' => 'French Republic', 'cca2' => 'FR', 'ccn3' => '250', 'cca3' => 'FRA', 'flag' => 'fr.svg', 'subregion_id' => '24'],
            ['currency_id' => 48, 'common' => 'French Guiana', 'official' => 'Guiana', 'cca2' => 'GF', 'ccn3' => '254', 'cca3' => 'GUF', 'flag' => 'gf.svg', 'subregion_id' => '17'],
            ['currency_id' => 31, 'common' => 'French Polynesia', 'official' => 'French Polynesia', 'cca2' => 'PF', 'ccn3' => '258', 'cca3' => 'PYF', 'flag' => 'pf.svg', 'subregion_id' => '16'],
            ['currency_id' => 48, 'common' => 'French Southern and Antarctic Lands', 'official' => 'Territory of the French Southern and Antarctic Lands', 'cca2' => 'TF', 'ccn3' => '260', 'cca3' => 'ATF', 'flag' => 'tf.svg', 'subregion_id' => '1'],
            ['currency_id' => 30, 'common' => 'Gabon', 'official' => 'Gabonese Republic', 'cca2' => 'GA', 'ccn3' => '266', 'cca3' => 'GAB', 'flag' => 'ga.svg', 'subregion_id' => '12'],
            ['currency_id' => 51, 'common' => 'Gambia', 'official' => 'Republic of the Gambia', 'cca2' => 'GM', 'ccn3' => '270', 'cca3' => 'GMB', 'flag' => 'gm.svg', 'subregion_id' => '22'],
            ['currency_id' => 52, 'common' => 'Georgia', 'official' => 'Georgia', 'cca2' => 'GE', 'ccn3' => '268', 'cca3' => 'GEO', 'flag' => 'ge.svg', 'subregion_id' => '23'],
            ['currency_id' => 48, 'common' => 'Germany', 'official' => 'Federal Republic of Germany', 'cca2' => 'DE', 'ccn3' => '276', 'cca3' => 'DEU', 'flag' => 'de.svg', 'subregion_id' => '24'],
            ['currency_id' => 53, 'common' => 'Ghana', 'official' => 'Republic of Ghana', 'cca2' => 'GH', 'ccn3' => '288', 'cca3' => 'GHA', 'flag' => 'gh.svg', 'subregion_id' => '22'],
            ['currency_id' => 54, 'common' => 'Gibraltar', 'official' => 'Gibraltar', 'cca2' => 'GI', 'ccn3' => '292', 'cca3' => 'GIB', 'flag' => 'gi.svg', 'subregion_id' => '21'],
            ['currency_id' => 48, 'common' => 'Greece', 'official' => 'Hellenic Republic', 'cca2' => 'GR', 'ccn3' => '300', 'cca3' => 'GRC', 'flag' => 'gr.svg', 'subregion_id' => '21'],
            ['currency_id' => 41, 'common' => 'Greenland', 'official' => 'Greenland', 'cca2' => 'GL', 'ccn3' => '304', 'cca3' => 'GRL', 'flag' => 'gl.svg', 'subregion_id' => '14'],
            ['currency_id' => 44, 'common' => 'Grenada', 'official' => 'Grenada', 'cca2' => 'GD', 'ccn3' => '308', 'cca3' => 'GRD', 'flag' => 'gd.svg', 'subregion_id' => '3'],
            ['currency_id' => 48, 'common' => 'Guadeloupe', 'official' => 'Guadeloupe', 'cca2' => 'GP', 'ccn3' => '312', 'cca3' => 'GLP', 'flag' => 'gp.svg', 'subregion_id' => '3'],
            ['currency_id' => 146, 'common' => 'Guam', 'official' => 'Guam', 'cca2' => 'GU', 'ccn3' => '316', 'cca3' => 'GUM', 'flag' => 'gu.svg', 'subregion_id' => '11'],
            ['currency_id' => 55, 'common' => 'Guatemala', 'official' => 'Republic of Guatemala', 'cca2' => 'GT', 'ccn3' => '320', 'cca3' => 'GTM', 'flag' => 'gt.svg', 'subregion_id' => '4'],
            ['currency_id' => 21, 'common' => 'Guernsey', 'official' => 'Bailiwick of Guernsey', 'cca2' => 'GG', 'ccn3' => '831', 'cca3' => 'GGY', 'flag' => 'gg.svg', 'subregion_id' => '15'],
            ['currency_id' => 56, 'common' => 'Guinea', 'official' => 'Republic of Guinea', 'cca2' => 'GN', 'ccn3' => '324', 'cca3' => 'GIN', 'flag' => 'gn.svg', 'subregion_id' => '22'],
            ['currency_id' => 153, 'common' => 'Guinea-Bissau', 'official' => 'Republic of Guinea-Bissau', 'cca2' => 'GW', 'ccn3' => '624', 'cca3' => 'GNB', 'flag' => 'gw.svg', 'subregion_id' => '22'],
            ['currency_id' => 57, 'common' => 'Guyana', 'official' => 'Co-operative Republic of Guyana', 'cca2' => 'GY', 'ccn3' => '328', 'cca3' => 'GUY', 'flag' => 'gy.svg', 'subregion_id' => '17'],
            ['currency_id' => 58, 'common' => 'Haiti', 'official' => 'Republic of Haiti', 'cca2' => 'HT', 'ccn3' => '332', 'cca3' => 'HTI', 'flag' => 'ht.svg', 'subregion_id' => '3'],
            ['currency_id' => 8, 'common' => 'Heard Island and McDonald Islands', 'official' => 'Heard Island and McDonald Islands', 'cca2' => 'HM', 'ccn3' => '334', 'cca3' => 'HMD', 'flag' => 'hm.svg', 'subregion_id' => '1'],
            ['currency_id' => 59, 'common' => 'Honduras', 'official' => 'Republic of Honduras', 'cca2' => 'HN', 'ccn3' => '340', 'cca3' => 'HND', 'flag' => 'hn.svg', 'subregion_id' => '4'],
            ['currency_id' => 60, 'common' => 'Hong Kong', 'official' => "Hong Kong Special Administrative Region of the People's Republic of China", 'cca2' => 'HK', 'ccn3' => '344', 'cca3' => 'HKG', 'flag' => 'hk.svg', 'subregion_id' => '8'],
            ['currency_id' => 61, 'common' => 'Hungary', 'official' => 'Hungary', 'cca2' => 'HU', 'ccn3' => '348', 'cca3' => 'HUN', 'flag' => 'hu.svg', 'subregion_id' => '6'],
            ['currency_id' => 62, 'common' => 'Iceland', 'official' => 'Iceland', 'cca2' => 'IS', 'ccn3' => '352', 'cca3' => 'ISL', 'flag' => 'is.svg', 'subregion_id' => '15'],
            ['currency_id' => 63, 'common' => 'India', 'official' => 'Republic of India', 'cca2' => 'IN', 'ccn3' => '356', 'cca3' => 'IND', 'flag' => 'in.svg', 'subregion_id' => '20'],
            ['currency_id' => 64, 'common' => 'Indonesia', 'official' => 'Republic of Indonesia', 'cca2' => 'ID', 'ccn3' => '360', 'cca3' => 'IDN', 'flag' => 'id.svg', 'subregion_id' => '18'],
            ['currency_id' => 65, 'common' => 'Iran', 'official' => 'Islamic Republic of Iran', 'cca2' => 'IR', 'ccn3' => '364', 'cca3' => 'IRN', 'flag' => 'ir.svg', 'subregion_id' => '20'],
            ['currency_id' => 66, 'common' => 'Iraq', 'official' => 'Republic of Iraq', 'cca2' => 'IQ', 'ccn3' => '368', 'cca3' => 'IRQ', 'flag' => 'iq.svg', 'subregion_id' => '23'],
            ['currency_id' => 48, 'common' => 'Ireland', 'official' => 'Republic of Ireland', 'cca2' => 'IE', 'ccn3' => '372', 'cca3' => 'IRL', 'flag' => 'ie.svg', 'subregion_id' => '15'],
            ['currency_id' => 21, 'common' => 'Isle of Man', 'official' => 'Isle of Man', 'cca2' => 'IM', 'ccn3' => '833', 'cca3' => 'IMN', 'flag' => 'im.svg', 'subregion_id' => '15'],
            ['currency_id' => 67, 'common' => 'Israel', 'official' => 'State of Israel', 'cca2' => 'IL', 'ccn3' => '376', 'cca3' => 'ISR', 'flag' => 'il.svg', 'subregion_id' => '23'],
            ['currency_id' => 48, 'common' => 'Italy', 'official' => 'Italian Republic', 'cca2' => 'IT', 'ccn3' => '380', 'cca3' => 'ITA', 'flag' => 'it.svg', 'subregion_id' => '21'],
            ['currency_id' => 153, 'common' => 'Ivory Coast', 'official' => "Republic of Côte d'Ivoire", 'cca2' => 'CI', 'ccn3' => '384', 'cca3' => 'CIV', 'flag' => 'ci.svg', 'subregion_id' => '22'],
            ['currency_id' => 69, 'common' => 'Jamaica', 'official' => 'Jamaica', 'cca2' => 'JM', 'ccn3' => '388', 'cca3' => 'JAM', 'flag' => 'jm.svg', 'subregion_id' => '3'],
            ['currency_id' => 70, 'common' => 'Japan', 'official' => 'Japan', 'cca2' => 'JP', 'ccn3' => '392', 'cca3' => 'JPN', 'flag' => 'jp.svg', 'subregion_id' => '8'],
            ['currency_id' => 21, 'common' => 'Jersey', 'official' => 'Bailiwick of Jersey', 'cca2' => 'JE', 'ccn3' => '832', 'cca3' => 'JEY', 'flag' => 'je.svg', 'subregion_id' => '15'],
            ['currency_id' => 71, 'common' => 'Jordan', 'official' => 'Hashemite Kingdom of Jordan', 'cca2' => 'JO', 'ccn3' => '400', 'cca3' => 'JOR', 'flag' => 'jo.svg', 'subregion_id' => '23'],
            ['currency_id' => 72, 'common' => 'Kazakhstan', 'official' => 'Republic of Kazakhstan', 'cca2' => 'KZ', 'ccn3' => '398', 'cca3' => 'KAZ', 'flag' => 'kz.svg', 'subregion_id' => '5'],
            ['currency_id' => 73, 'common' => 'Kenya', 'official' => 'Republic of Kenya', 'cca2' => 'KE', 'ccn3' => '404', 'cca3' => 'KEN', 'flag' => 'ke.svg', 'subregion_id' => '7'],
            ['currency_id' => 8, 'common' => 'Kiribati', 'official' => 'Independent and Sovereign Republic of Kiribati', 'cca2' => 'KI', 'ccn3' => '296', 'cca3' => 'KIR', 'flag' => 'ki.svg', 'subregion_id' => '11'],
            ['currency_id' => 48, 'common' => 'Kosovo', 'official' => 'Republic of Kosovo', 'cca2' => 'XK', 'ccn3' => '', 'cca3' => 'UNK', 'flag' => 'xk.svg', 'subregion_id' => '21'],
            ['currency_id' => 74, 'common' => 'Kuwait', 'official' => 'State of Kuwait', 'cca2' => 'KW', 'ccn3' => '414', 'cca3' => 'KWT', 'flag' => 'kw.svg', 'subregion_id' => '23'],
            ['currency_id' => 75, 'common' => 'Kyrgyzstan', 'official' => 'Kyrgyz Republic', 'cca2' => 'KG', 'ccn3' => '417', 'cca3' => 'KGZ', 'flag' => 'kg.svg', 'subregion_id' => '5'],
            ['currency_id' => 76, 'common' => 'Laos', 'official' => "Lao People's Democratic Republic", 'cca2' => 'LA', 'ccn3' => '418', 'cca3' => 'LAO', 'flag' => 'la.svg', 'subregion_id' => '18'],
            ['currency_id' => 48, 'common' => 'Latvia', 'official' => 'Republic of Latvia', 'cca2' => 'LV', 'ccn3' => '428', 'cca3' => 'LVA', 'flag' => 'lv.svg', 'subregion_id' => '15'],
            ['currency_id' => 77, 'common' => 'Lebanon', 'official' => 'Lebanese Republic', 'cca2' => 'LB', 'ccn3' => '422', 'cca3' => 'LBN', 'flag' => 'lb.svg', 'subregion_id' => '23'],
            ['currency_id' => 78, 'common' => 'Lesotho', 'official' => 'Kingdom of Lesotho', 'cca2' => 'LS', 'ccn3' => '426', 'cca3' => 'LSO', 'flag' => 'ls.svg', 'subregion_id' => '19'],
            ['currency_id' => 79, 'common' => 'Liberia', 'official' => 'Republic of Liberia', 'cca2' => 'LR', 'ccn3' => '430', 'cca3' => 'LBR', 'flag' => 'lr.svg', 'subregion_id' => '22'],
            ['currency_id' => 80, 'common' => 'Libya', 'official' => 'State of Libya', 'cca2' => 'LY', 'ccn3' => '434', 'cca3' => 'LBY', 'flag' => 'ly.svg', 'subregion_id' => '13'],
            ['currency_id' => 133, 'common' => 'Liechtenstein', 'official' => 'Principality of Liechtenstein', 'cca2' => 'LI', 'ccn3' => '438', 'cca3' => 'LIE', 'flag' => 'li.svg', 'subregion_id' => '24'],
            ['currency_id' => 48, 'common' => 'Lithuania', 'official' => 'Republic of Lithuania', 'cca2' => 'LT', 'ccn3' => '440', 'cca3' => 'LTU', 'flag' => 'lt.svg', 'subregion_id' => '15'],
            ['currency_id' => 48, 'common' => 'Luxembourg', 'official' => 'Grand Duchy of Luxembourg', 'cca2' => 'LU', 'ccn3' => '442', 'cca3' => 'LUX', 'flag' => 'lu.svg', 'subregion_id' => '24'],
            ['currency_id' => 81, 'common' => 'Macau', 'official' => "Macao Special Administrative Region of the People's Republic of China", 'cca2' => 'MO', 'ccn3' => '446', 'cca3' => 'MAC', 'flag' => 'mo.svg', 'subregion_id' => '8'],
            ['currency_id' => 83, 'common' => 'Madagascar', 'official' => 'Republic of Madagascar', 'cca2' => 'MG', 'ccn3' => '450', 'cca3' => 'MDG', 'flag' => 'mg.svg', 'subregion_id' => '7'],
            ['currency_id' => 84, 'common' => 'Malawi', 'official' => 'Republic of Malawi', 'cca2' => 'MW', 'ccn3' => '454', 'cca3' => 'MWI', 'flag' => 'mw.svg', 'subregion_id' => '7'],
            ['currency_id' => 85, 'common' => 'Malaysia', 'official' => 'Malaysia', 'cca2' => 'MY', 'ccn3' => '458', 'cca3' => 'MYS', 'flag' => 'my.svg', 'subregion_id' => '18'],
            ['currency_id' => 86, 'common' => 'Maldives', 'official' => 'Republic of the Maldives', 'cca2' => 'MV', 'ccn3' => '462', 'cca3' => 'MDV', 'flag' => 'mv.svg', 'subregion_id' => '20'],
            ['currency_id' => 153, 'common' => 'Mali', 'official' => 'Republic of Mali', 'cca2' => 'ML', 'ccn3' => '466', 'cca3' => 'MLI', 'flag' => 'ml.svg', 'subregion_id' => '22'],
            ['currency_id' => 48, 'common' => 'Malta', 'official' => 'Republic of Malta', 'cca2' => 'MT', 'ccn3' => '470', 'cca3' => 'MLT', 'flag' => 'mt.svg', 'subregion_id' => '21'],
            ['currency_id' => 146, 'common' => 'Marshall Islands', 'official' => 'Republic of the Marshall Islands', 'cca2' => 'MH', 'ccn3' => '584', 'cca3' => 'MHL', 'flag' => 'mh.svg', 'subregion_id' => '11'],
            ['currency_id' => 48, 'common' => 'Martinique', 'official' => 'Martinique', 'cca2' => 'MQ', 'ccn3' => '474', 'cca3' => 'MTQ', 'flag' => 'mq.svg', 'subregion_id' => '3'],
            ['currency_id' => 87, 'common' => 'Mauritania', 'official' => 'Islamic Republic of Mauritania', 'cca2' => 'MR', 'ccn3' => '478', 'cca3' => 'MRT', 'flag' => 'mr.svg', 'subregion_id' => '22'],
            ['currency_id' => 88, 'common' => 'Mauritius', 'official' => 'Republic of Mauritius', 'cca2' => 'MU', 'ccn3' => '480', 'cca3' => 'MUS', 'flag' => 'mu.svg', 'subregion_id' => '7'],
            ['currency_id' => 48, 'common' => 'Mayotte', 'official' => 'Department of Mayotte', 'cca2' => 'YT', 'ccn3' => '175', 'cca3' => 'MYT', 'flag' => 'yt.svg', 'subregion_id' => '7'],
            ['currency_id' => 89, 'common' => 'Mexico', 'official' => 'United Mexican States', 'cca2' => 'MX', 'ccn3' => '484', 'cca3' => 'MEX', 'flag' => 'mx.svg', 'subregion_id' => '14'],
            ['currency_id' => 146, 'common' => 'Micronesia', 'official' => 'Federated States of Micronesia', 'cca2' => 'FM', 'ccn3' => '583', 'cca3' => 'FSM', 'flag' => 'fm.svg', 'subregion_id' => '11'],
            ['currency_id' => 90, 'common' => 'Moldova', 'official' => 'Republic of Moldova', 'cca2' => 'MD', 'ccn3' => '498', 'cca3' => 'MDA', 'flag' => 'md.svg', 'subregion_id' => '9'],
            ['currency_id' => 48, 'common' => 'Monaco', 'official' => 'Principality of Monaco', 'cca2' => 'MC', 'ccn3' => '492', 'cca3' => 'MCO', 'flag' => 'mc.svg', 'subregion_id' => '24'],
            ['currency_id' => 91, 'common' => 'Mongolia', 'official' => 'Mongolia', 'cca2' => 'MN', 'ccn3' => '496', 'cca3' => 'MNG', 'flag' => 'mn.svg', 'subregion_id' => '8'],
            ['currency_id' => 48, 'common' => 'Montenegro', 'official' => 'Montenegro', 'cca2' => 'ME', 'ccn3' => '499', 'cca3' => 'MNE', 'flag' => 'me.svg', 'subregion_id' => '21'],
            ['currency_id' => 44, 'common' => 'Montserrat', 'official' => 'Montserrat', 'cca2' => 'MS', 'ccn3' => '500', 'cca3' => 'MSR', 'flag' => 'ms.svg', 'subregion_id' => '3'],
            ['currency_id' => 92, 'common' => 'Morocco', 'official' => 'Kingdom of Morocco', 'cca2' => 'MA', 'ccn3' => '504', 'cca3' => 'MAR', 'flag' => 'ma.svg', 'subregion_id' => '13'],
            ['currency_id' => 93, 'common' => 'Mozambique', 'official' => 'Republic of Mozambique', 'cca2' => 'MZ', 'ccn3' => '508', 'cca3' => 'MOZ', 'flag' => 'mz.svg', 'subregion_id' => '7'],
            ['currency_id' => 24, 'common' => 'Myanmar', 'official' => 'Republic of the Union of Myanmar', 'cca2' => 'MM', 'ccn3' => '104', 'cca3' => 'MMR', 'flag' => 'mm.svg', 'subregion_id' => '18'],
            ['currency_id' => 94, 'common' => 'Namibia', 'official' => 'Republic of Namibia', 'cca2' => 'NA', 'ccn3' => '516', 'cca3' => 'NAM', 'flag' => 'na.svg', 'subregion_id' => '19'],
            ['currency_id' => 8, 'common' => 'Nauru', 'official' => 'Republic of Nauru', 'cca2' => 'NR', 'ccn3' => '520', 'cca3' => 'NRU', 'flag' => 'nr.svg', 'subregion_id' => '11'],
            ['currency_id' => 95, 'common' => 'Nepal', 'official' => 'Federal Democratic Republic of Nepal', 'cca2' => 'NP', 'ccn3' => '524', 'cca3' => 'NPL', 'flag' => 'np.svg', 'subregion_id' => '20'],
            ['currency_id' => 48, 'common' => 'Netherlands', 'official' => 'Kingdom of the Netherlands', 'cca2' => 'NL', 'ccn3' => '528', 'cca3' => 'NLD', 'flag' => 'nl.svg', 'subregion_id' => '24'],
            ['currency_id' => 31, 'common' => 'New Caledonia', 'official' => 'New Caledonia', 'cca2' => 'NC', 'ccn3' => '540', 'cca3' => 'NCL', 'flag' => 'nc.svg', 'subregion_id' => '10'],
            ['currency_id' => 99, 'common' => 'New Zealand', 'official' => 'New Zealand', 'cca2' => 'NZ', 'ccn3' => '554', 'cca3' => 'NZL', 'flag' => 'nz.svg', 'subregion_id' => '2'],
            ['currency_id' => 100, 'common' => 'Nicaragua', 'official' => 'Republic of Nicaragua', 'cca2' => 'NI', 'ccn3' => '558', 'cca3' => 'NIC', 'flag' => 'ni.svg', 'subregion_id' => '4'],
            ['currency_id' => 153, 'common' => 'Niger', 'official' => 'Republic of Niger', 'cca2' => 'NE', 'ccn3' => '562', 'cca3' => 'NER', 'flag' => 'ne.svg', 'subregion_id' => '22'],
            ['currency_id' => 101, 'common' => 'Nigeria', 'official' => 'Federal Republic of Nigeria', 'cca2' => 'NG', 'ccn3' => '566', 'cca3' => 'NGA', 'flag' => 'ng.svg', 'subregion_id' => '22'],
            ['currency_id' => 99, 'common' => 'Niue', 'official' => 'Niue', 'cca2' => 'NU', 'ccn3' => '570', 'cca3' => 'NIU', 'flag' => 'nu.svg', 'subregion_id' => '16'],
            ['currency_id' => 8, 'common' => 'Norfolk Island', 'official' => 'Territory of Norfolk Island', 'cca2' => 'NF', 'ccn3' => '574', 'cca3' => 'NFK', 'flag' => 'nf.svg', 'subregion_id' => '2'],
            ['currency_id' => 102, 'common' => 'North Korea', 'official' => "Democratic People's Republic of Korea", 'cca2' => 'KP', 'ccn3' => '408', 'cca3' => 'PRK', 'flag' => 'kp.svg', 'subregion_id' => '8'],
            ['currency_id' => 82, 'common' => 'North Macedonia', 'official' => 'Republic of North Macedonia', 'cca2' => 'MK', 'ccn3' => '807', 'cca3' => 'MKD', 'flag' => 'mk.svg', 'subregion_id' => '21'],
            ['currency_id' => 146, 'common' => 'Northern Mariana Islands', 'official' => 'Commonwealth of the Northern Mariana Islands', 'cca2' => 'MP', 'ccn3' => '580', 'cca3' => 'MNP', 'flag' => 'mp.svg', 'subregion_id' => '11'],
            ['currency_id' => 103, 'common' => 'Norway', 'official' => 'Kingdom of Norway', 'cca2' => 'NO', 'ccn3' => '578', 'cca3' => 'NOR', 'flag' => 'no.svg', 'subregion_id' => '15'],
            ['currency_id' => 104, 'common' => 'Oman', 'official' => 'Sultanate of Oman', 'cca2' => 'OM', 'ccn3' => '512', 'cca3' => 'OMN', 'flag' => 'om.svg', 'subregion_id' => '23'],
            ['currency_id' => 105, 'common' => 'Pakistan', 'official' => 'Islamic Republic of Pakistan', 'cca2' => 'PK', 'ccn3' => '586', 'cca3' => 'PAK', 'flag' => 'pk.svg', 'subregion_id' => '20'],
            ['currency_id' => 146, 'common' => 'Palau', 'official' => 'Republic of Palau', 'cca2' => 'PW', 'ccn3' => '585', 'cca3' => 'PLW', 'flag' => 'pw.svg', 'subregion_id' => '11'],
            ['currency_id' => 67, 'common' => 'Palestine', 'official' => 'State of Palestine', 'cca2' => 'PS', 'ccn3' => '275', 'cca3' => 'PSE', 'flag' => 'ps.svg', 'subregion_id' => '23'],
            ['currency_id' => 106, 'common' => 'Panama', 'official' => 'Republic of Panama', 'cca2' => 'PA', 'ccn3' => '591', 'cca3' => 'PAN', 'flag' => 'pa.svg', 'subregion_id' => '4'],
            ['currency_id' => 107, 'common' => 'Papua New Guinea', 'official' => 'Independent State of Papua New Guinea', 'cca2' => 'PG', 'ccn3' => '598', 'cca3' => 'PNG', 'flag' => 'pg.svg', 'subregion_id' => '10'],
            ['currency_id' => 108, 'common' => 'Paraguay', 'official' => 'Republic of Paraguay', 'cca2' => 'PY', 'ccn3' => '600', 'cca3' => 'PRY', 'flag' => 'py.svg', 'subregion_id' => '17'],
            ['currency_id' => 109, 'common' => 'Peru', 'official' => 'Republic of Peru', 'cca2' => 'PE', 'ccn3' => '604', 'cca3' => 'PER', 'flag' => 'pe.svg', 'subregion_id' => '17'],
            ['currency_id' => 110, 'common' => 'Philippines', 'official' => 'Republic of the Philippines', 'cca2' => 'PH', 'ccn3' => '608', 'cca3' => 'PHL', 'flag' => 'ph.svg', 'subregion_id' => '18'],
            ['currency_id' => 99, 'common' => 'Pitcairn Islands', 'official' => 'Pitcairn Group of Islands', 'cca2' => 'PN', 'ccn3' => '612', 'cca3' => 'PCN', 'flag' => 'pn.svg', 'subregion_id' => '16'],
            ['currency_id' => 111, 'common' => 'Poland', 'official' => 'Republic of Poland', 'cca2' => 'PL', 'ccn3' => '616', 'cca3' => 'POL', 'flag' => 'pl.svg', 'subregion_id' => '6'],
            ['currency_id' => 48, 'common' => 'Portugal', 'official' => 'Portuguese Republic', 'cca2' => 'PT', 'ccn3' => '620', 'cca3' => 'PRT', 'flag' => 'pt.svg', 'subregion_id' => '21'],
            ['currency_id' => 146, 'common' => 'Puerto Rico', 'official' => 'Commonwealth of Puerto Rico', 'cca2' => 'PR', 'ccn3' => '630', 'cca3' => 'PRI', 'flag' => 'pr.svg', 'subregion_id' => '3'],
            ['currency_id' => 112, 'common' => 'Qatar', 'official' => 'State of Qatar', 'cca2' => 'QA', 'ccn3' => '634', 'cca3' => 'QAT', 'flag' => 'qa.svg', 'subregion_id' => '23'],
            ['currency_id' => 30, 'common' => 'Republic of the Congo', 'official' => 'Republic of the Congo', 'cca2' => 'CG', 'ccn3' => '178', 'cca3' => 'COG', 'flag' => 'cg.svg', 'subregion_id' => '12'],
            ['currency_id' => 48, 'common' => 'Réunion', 'official' => 'Réunion Island', 'cca2' => 'RE', 'ccn3' => '638', 'cca3' => 'REU', 'flag' => 're.svg', 'subregion_id' => '7'],
            ['currency_id' => 113, 'common' => 'Romania', 'official' => 'Romania', 'cca2' => 'RO', 'ccn3' => '642', 'cca3' => 'ROU', 'flag' => 'ro.svg', 'subregion_id' => '21'],
            ['currency_id' => 114, 'common' => 'Russia', 'official' => 'Russian Federation', 'cca2' => 'RU', 'ccn3' => '643', 'cca3' => 'RUS', 'flag' => 'ru.svg', 'subregion_id' => '9'],
            ['currency_id' => 115, 'common' => 'Rwanda', 'official' => 'Republic of Rwanda', 'cca2' => 'RW', 'ccn3' => '646', 'cca3' => 'RWA', 'flag' => 'rw.svg', 'subregion_id' => '7'],
            ['currency_id' => 48, 'common' => 'Saint Barthélemy', 'official' => 'Collectivity of Saint Barthélemy', 'cca2' => 'BL', 'ccn3' => '652', 'cca3' => 'BLM', 'flag' => 'bl.svg', 'subregion_id' => '3'],
            ['currency_id' => 116, 'common' => 'Saint Helena, Ascension and Tristan da Cunha', 'official' => 'Saint Helena, Ascension and Tristan da Cunha', 'cca2' => 'SH', 'ccn3' => '654', 'cca3' => 'SHN', 'flag' => 'sh.svg', 'subregion_id' => '22'],
            ['currency_id' => 44, 'common' => 'Saint Kitts and Nevis', 'official' => 'Federation of Saint Christopher and Nevis', 'cca2' => 'KN', 'ccn3' => '659', 'cca3' => 'KNA', 'flag' => 'kn.svg', 'subregion_id' => '3'],
            ['currency_id' => 44, 'common' => 'Saint Lucia', 'official' => 'Saint Lucia', 'cca2' => 'LC', 'ccn3' => '662', 'cca3' => 'LCA', 'flag' => 'lc.svg', 'subregion_id' => '3'],
            ['currency_id' => 48, 'common' => 'Saint Martin', 'official' => 'Saint Martin', 'cca2' => 'MF', 'ccn3' => '663', 'cca3' => 'MAF', 'flag' => 'mf.svg', 'subregion_id' => '3'],
            ['currency_id' => 48, 'common' => 'Saint Pierre and Miquelon', 'official' => 'Saint Pierre and Miquelon', 'cca2' => 'PM', 'ccn3' => '666', 'cca3' => 'SPM', 'flag' => 'pm.svg', 'subregion_id' => '14'],
            ['currency_id' => 44, 'common' => 'Saint Vincent and the Grenadines', 'official' => 'Saint Vincent and the Grenadines', 'cca2' => 'VC', 'ccn3' => '670', 'cca3' => 'VCT', 'flag' => 'vc.svg', 'subregion_id' => '3'],
            ['currency_id' => 117, 'common' => 'Samoa', 'official' => 'Independent State of Samoa', 'cca2' => 'WS', 'ccn3' => '882', 'cca3' => 'WSM', 'flag' => 'ws.svg', 'subregion_id' => '16'],
            ['currency_id' => 48, 'common' => 'San Marino', 'official' => 'Republic of San Marino', 'cca2' => 'SM', 'ccn3' => '674', 'cca3' => 'SMR', 'flag' => 'sm.svg', 'subregion_id' => '21'],
            ['currency_id' => 118, 'common' => 'São Tomé and Príncipe', 'official' => 'Democratic Republic of São Tomé and Príncipe', 'cca2' => 'ST', 'ccn3' => '678', 'cca3' => 'STP', 'flag' => 'st.svg', 'subregion_id' => '12'],
            ['currency_id' => 119, 'common' => 'Saudi Arabia', 'official' => 'Kingdom of Saudi Arabia', 'cca2' => 'SA', 'ccn3' => '682', 'cca3' => 'SAU', 'flag' => 'sa.svg', 'subregion_id' => '23'],
            ['currency_id' => 153, 'common' => 'Senegal', 'official' => 'Republic of Senegal', 'cca2' => 'SN', 'ccn3' => '686', 'cca3' => 'SEN', 'flag' => 'sn.svg', 'subregion_id' => '22'],
            ['currency_id' => 120, 'common' => 'Serbia', 'official' => 'Republic of Serbia', 'cca2' => 'RS', 'ccn3' => '688', 'cca3' => 'SRB', 'flag' => 'rs.svg', 'subregion_id' => '21'],
            ['currency_id' => 121, 'common' => 'Seychelles', 'official' => 'Republic of Seychelles', 'cca2' => 'SC', 'ccn3' => '690', 'cca3' => 'SYC', 'flag' => 'sc.svg', 'subregion_id' => '7'],
            ['currency_id' => 122, 'common' => 'Sierra Leone', 'official' => 'Republic of Sierra Leone', 'cca2' => 'SL', 'ccn3' => '694', 'cca3' => 'SLE', 'flag' => 'sl.svg', 'subregion_id' => '22'],
            ['currency_id' => 22, 'common' => 'Singapore', 'official' => 'Republic of Singapore', 'cca2' => 'SG', 'ccn3' => '702', 'cca3' => 'SGP', 'flag' => 'sg.svg', 'subregion_id' => '18'],
            ['currency_id' => 96, 'common' => 'Sint Maarten', 'official' => 'Sint Maarten', 'cca2' => 'SX', 'ccn3' => '534', 'cca3' => 'SXM', 'flag' => 'sx.svg', 'subregion_id' => '3'],
            ['currency_id' => 48, 'common' => 'Slovakia', 'official' => 'Slovak Republic', 'cca2' => 'SK', 'ccn3' => '703', 'cca3' => 'SVK', 'flag' => 'sk.svg', 'subregion_id' => '6'],
            ['currency_id' => 48, 'common' => 'Slovenia', 'official' => 'Republic of Slovenia', 'cca2' => 'SI', 'ccn3' => '705', 'cca3' => 'SVN', 'flag' => 'si.svg', 'subregion_id' => '6'],
            ['currency_id' => 123, 'common' => 'Solomon Islands', 'official' => 'Solomon Islands', 'cca2' => 'SB', 'ccn3' => '090', 'cca3' => 'SLB', 'flag' => 'sb.svg', 'subregion_id' => '10'],
            ['currency_id' => 124, 'common' => 'Somalia', 'official' => 'Federal Republic of Somalia', 'cca2' => 'SO', 'ccn3' => '706', 'cca3' => 'SOM', 'flag' => 'so.svg', 'subregion_id' => '7'],
            ['currency_id' => 125, 'common' => 'South Africa', 'official' => 'Republic of South Africa', 'cca2' => 'ZA', 'ccn3' => '710', 'cca3' => 'ZAF', 'flag' => 'za.svg', 'subregion_id' => '19'],
            ['currency_id' => 21, 'common' => 'South Georgia', 'official' => 'South Georgia and the South Sandwich Islands', 'cca2' => 'GS', 'ccn3' => '239', 'cca3' => 'SGS', 'flag' => 'gs.svg', 'subregion_id' => '1'],
            ['currency_id' => 126, 'common' => 'South Korea', 'official' => 'Republic of Korea', 'cca2' => 'KR', 'ccn3' => '410', 'cca3' => 'KOR', 'flag' => 'kr.svg', 'subregion_id' => '8'],
            ['currency_id' => 127, 'common' => 'South Sudan', 'official' => 'Republic of South Sudan', 'cca2' => 'SS', 'ccn3' => '728', 'cca3' => 'SSD', 'flag' => 'ss.svg', 'subregion_id' => '12'],
            ['currency_id' => 48, 'common' => 'Spain', 'official' => 'Kingdom of Spain', 'cca2' => 'ES', 'ccn3' => '724', 'cca3' => 'ESP', 'flag' => 'es.svg', 'subregion_id' => '21'],
            ['currency_id' => 128, 'common' => 'Sri Lanka', 'official' => 'Democratic Socialist Republic of Sri Lanka', 'cca2' => 'LK', 'ccn3' => '144', 'cca3' => 'LKA', 'flag' => 'lk.svg', 'subregion_id' => '20'],
            ['currency_id' => 129, 'common' => 'Sudan', 'official' => 'Republic of the Sudan', 'cca2' => 'SD', 'ccn3' => '729', 'cca3' => 'SDN', 'flag' => 'sd.svg', 'subregion_id' => '13'],
            ['currency_id' => 130, 'common' => 'Suriname', 'official' => 'Republic of Suriname', 'cca2' => 'SR', 'ccn3' => '740', 'cca3' => 'SUR', 'flag' => 'sr.svg', 'subregion_id' => '17'],
            ['currency_id' => 103, 'common' => 'Svalbard and Jan Mayen', 'official' => 'Svalbard og Jan Mayen', 'cca2' => 'SJ', 'ccn3' => '744', 'cca3' => 'SJM', 'flag' => 'sj.svg', 'subregion_id' => '15'],
            ['currency_id' => 132, 'common' => 'Sweden', 'official' => 'Kingdom of Sweden', 'cca2' => 'SE', 'ccn3' => '752', 'cca3' => 'SWE', 'flag' => 'se.svg', 'subregion_id' => '15'],
            ['currency_id' => 133, 'common' => 'Switzerland', 'official' => 'Swiss Confederation', 'cca2' => 'CH', 'ccn3' => '756', 'cca3' => 'CHE', 'flag' => 'ch.svg', 'subregion_id' => '24'],
            ['currency_id' => 134, 'common' => 'Syria', 'official' => 'Syrian Arab Republic', 'cca2' => 'SY', 'ccn3' => '760', 'cca3' => 'SYR', 'flag' => 'sy.svg', 'subregion_id' => '23'],
            ['currency_id' => 98, 'common' => 'Taiwan', 'official' => 'Republic of China (Taiwan)', 'cca2' => 'TW', 'ccn3' => '158', 'cca3' => 'TWN', 'flag' => 'tw.svg', 'subregion_id' => '8'],
            ['currency_id' => 135, 'common' => 'Tajikistan', 'official' => 'Republic of Tajikistan', 'cca2' => 'TJ', 'ccn3' => '762', 'cca3' => 'TJK', 'flag' => 'tj.svg', 'subregion_id' => '5'],
            ['currency_id' => 136, 'common' => 'Tanzania', 'official' => 'United Republic of Tanzania', 'cca2' => 'TZ', 'ccn3' => '834', 'cca3' => 'TZA', 'flag' => 'tz.svg', 'subregion_id' => '7'],
            ['currency_id' => 137, 'common' => 'Thailand', 'official' => 'Kingdom of Thailand', 'cca2' => 'TH', 'ccn3' => '764', 'cca3' => 'THA', 'flag' => 'th.svg', 'subregion_id' => '18'],
            ['currency_id' => 146, 'common' => 'Timor-Leste', 'official' => 'Democratic Republic of Timor-Leste', 'cca2' => 'TL', 'ccn3' => '626', 'cca3' => 'TLS', 'flag' => 'tl.svg', 'subregion_id' => '18'],
            ['currency_id' => 153, 'common' => 'Togo', 'official' => 'Togolese Republic', 'cca2' => 'TG', 'ccn3' => '768', 'cca3' => 'TGO', 'flag' => 'tg.svg', 'subregion_id' => '22'],
            ['currency_id' => 99, 'common' => 'Tokelau', 'official' => 'Tokelau', 'cca2' => 'TK', 'ccn3' => '772', 'cca3' => 'TKL', 'flag' => 'tk.svg', 'subregion_id' => '16'],
            ['currency_id' => 138, 'common' => 'Tonga', 'official' => 'Kingdom of Tonga', 'cca2' => 'TO', 'ccn3' => '776', 'cca3' => 'TON', 'flag' => 'to.svg', 'subregion_id' => '16'],
            ['currency_id' => 139, 'common' => 'Trinidad and Tobago', 'official' => 'Republic of Trinidad and Tobago', 'cca2' => 'TT', 'ccn3' => '780', 'cca3' => 'TTO', 'flag' => 'tt.svg', 'subregion_id' => '3'],
            ['currency_id' => 140, 'common' => 'Tunisia', 'official' => 'Tunisian Republic', 'cca2' => 'TN', 'ccn3' => '788', 'cca3' => 'TUN', 'flag' => 'tn.svg', 'subregion_id' => '13'],
            ['currency_id' => 141, 'common' => 'Turkey', 'official' => 'Republic of Turkey', 'cca2' => 'TR', 'ccn3' => '792', 'cca3' => 'TUR', 'flag' => 'tr.svg', 'subregion_id' => '23'],
            ['currency_id' => 142, 'common' => 'Turkmenistan', 'official' => 'Turkmenistan', 'cca2' => 'TM', 'ccn3' => '795', 'cca3' => 'TKM', 'flag' => 'tm.svg', 'subregion_id' => '5'],
            ['currency_id' => 146, 'common' => 'Turks and Caicos Islands', 'official' => 'Turks and Caicos Islands', 'cca2' => 'TC', 'ccn3' => '796', 'cca3' => 'TCA', 'flag' => 'tc.svg', 'subregion_id' => '3'],
            ['currency_id' => 8, 'common' => 'Tuvalu', 'official' => 'Tuvalu', 'cca2' => 'TV', 'ccn3' => '798', 'cca3' => 'TUV', 'flag' => 'tv.svg', 'subregion_id' => '16'],
            ['currency_id' => 143, 'common' => 'Uganda', 'official' => 'Republic of Uganda', 'cca2' => 'UG', 'ccn3' => '800', 'cca3' => 'UGA', 'flag' => 'ug.svg', 'subregion_id' => '7'],
            ['currency_id' => 144, 'common' => 'Ukraine', 'official' => 'Ukraine', 'cca2' => 'UA', 'ccn3' => '804', 'cca3' => 'UKR', 'flag' => 'ua.svg', 'subregion_id' => '9'],
            ['currency_id' => 145, 'common' => 'United Arab Emirates', 'official' => 'United Arab Emirates', 'cca2' => 'AE', 'ccn3' => '784', 'cca3' => 'ARE', 'flag' => 'ae.svg', 'subregion_id' => '23'],
            ['currency_id' => 21, 'common' => 'United Kingdom', 'official' => 'United Kingdom of Great Britain and Northern Ireland', 'cca2' => 'GB', 'ccn3' => '826', 'cca3' => 'GBR', 'flag' => 'gb.svg', 'subregion_id' => '15'],
            ['currency_id' => 146, 'common' => 'United States', 'official' => 'United States of America', 'cca2' => 'US', 'ccn3' => '840', 'cca3' => 'USA', 'flag' => 'us.svg', 'subregion_id' => '14'],
            ['currency_id' => 146, 'common' => 'United States Minor Outlying Islands', 'official' => 'United States Minor Outlying Islands', 'cca2' => 'UM', 'ccn3' => '581', 'cca3' => 'UMI', 'flag' => 'um.svg', 'subregion_id' => '14'],
            ['currency_id' => 146, 'common' => 'United States Virgin Islands', 'official' => 'Virgin Islands of the United States', 'cca2' => 'VI', 'ccn3' => '850', 'cca3' => 'VIR', 'flag' => 'vi.svg', 'subregion_id' => '3'],
            ['currency_id' => 148, 'common' => 'Uruguay', 'official' => 'Oriental Republic of Uruguay', 'cca2' => 'UY', 'ccn3' => '858', 'cca3' => 'URY', 'flag' => 'uy.svg', 'subregion_id' => '17'],
            ['currency_id' => 149, 'common' => 'Uzbekistan', 'official' => 'Republic of Uzbekistan', 'cca2' => 'UZ', 'ccn3' => '860', 'cca3' => 'UZB', 'flag' => 'uz.svg', 'subregion_id' => '5'],
            ['currency_id' => 150, 'common' => 'Vanuatu', 'official' => 'Republic of Vanuatu', 'cca2' => 'VU', 'ccn3' => '548', 'cca3' => 'VUT', 'flag' => 'vu.svg', 'subregion_id' => '10'],
            ['currency_id' => 48, 'common' => 'Vatican City', 'official' => 'Vatican City State', 'cca2' => 'VA', 'ccn3' => '336', 'cca3' => 'VAT', 'flag' => 'va.svg', 'subregion_id' => '21'],
            ['currency_id' => 151, 'common' => 'Venezuela', 'official' => 'Bolivarian Republic of Venezuela', 'cca2' => 'VE', 'ccn3' => '862', 'cca3' => 'VEN', 'flag' => 've.svg', 'subregion_id' => '17'],
            ['currency_id' => 152, 'common' => 'Vietnam', 'official' => 'Socialist Republic of Vietnam', 'cca2' => 'VN', 'ccn3' => '704', 'cca3' => 'VNM', 'flag' => 'vn.svg', 'subregion_id' => '18'],
            ['currency_id' => 31, 'common' => 'Wallis and Futuna', 'official' => 'Territory of the Wallis and Futuna Islands', 'cca2' => 'WF', 'ccn3' => '876', 'cca3' => 'WLF', 'flag' => 'wf.svg', 'subregion_id' => '16'],
            ['currency_id' => 92, 'common' => 'Western Sahara', 'official' => 'Sahrawi Arab Democratic Republic', 'cca2' => 'EH', 'ccn3' => '732', 'cca3' => 'ESH', 'flag' => 'eh.svg', 'subregion_id' => '13'],
            ['currency_id' => 154, 'common' => 'Yemen', 'official' => 'Republic of Yemen', 'cca2' => 'YE', 'ccn3' => '887', 'cca3' => 'YEM', 'flag' => 'ye.svg', 'subregion_id' => '23'],
            ['currency_id' => 155, 'common' => 'Zambia', 'official' => 'Republic of Zambia', 'cca2' => 'ZM', 'ccn3' => '894', 'cca3' => 'ZMB', 'flag' => 'zm.svg', 'subregion_id' => '7'],
            ['currency_id' => 19, 'common' => 'Zimbabwe', 'official' => 'Republic of Zimbabwe', 'cca2' => 'ZW', 'ccn3' => '716', 'cca3' => 'ZWE', 'flag' => 'zw.svg', 'subregion_id' => '19'],
        ];

        foreach ($countries as $country) {
            $newCountry = new Country();
            $newCountry->common = $country['common'];
            $newCountry->official = $country['official'];
            $newCountry->cca2 = $country['cca2'];
            $newCountry->ccn3 = $country['ccn3'];
            $newCountry->cca3 = $country['cca3'];
            $newCountry->flag = $country['flag'];
            $newCountry->subregion_id = $country['subregion_id'];
            $newCountry->currency_id = $country['currency_id'];
            $newCountry->save();

        }
    }
}
